databases:
  - name: telemedicine
    plan: free
    databaseName: tms_xiit
    user: 

services:
  - type: web
    plan: free
    name: telemedicine
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn telemedicine.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tms_xiit
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4